const Menu=[{
    id:1,
    image:"Images/oats.jpg",
    name:"Oats",
    category:"Breakfast",
    prize:"100₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.",
},{
    id:2,
    image:"Images/Biriyani.jpg",
    name:"Biriyani",
    category:"Lunch",
    prize:"200₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:3,
    image:"Images/badam-halwa.jpg",
    name:"Garam Siro",
    category:"Lunch",
    prize:"100₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:4,
    image:"Images/omlette.jpg",
    name:"Omlate",
    category:"Breakfast",
    prize:"40₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:5,
    image:"Images/panjabi.jpg",
    name:"Panjabi Dish",
    category:"Dinner",
    prize:"120₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:6,
    image:"Images/coffee.jpg",
    name:"coffee",
    category:"Breakfast",
    prize:"50₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:7,
    image:"Images/hamburger.jpg",
    name:"Burger",
    category:"Evening",
    prize:"70₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:8,
    image:"Images/plums.jpg",
    name:"plums",
    category:"Evening",
    prize:"90₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
},
{
    id:9,
    image:"Images/pizza.jpg",
    name:"pizza",
    category:"Dinner",
    prize:"700₹",
    discription:"  Ots is a best Breakfast Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nam possimus dignissimos et facilis voluptatibus aut, rerum placeat eaque distinctio.", 
}
]
export default Menu;